name: CI + CD | Build images, push to ECR, apply Terraform

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraformfiles

    # 👇 Set environment variables required for all steps
    env:
      AWS_REGION:            ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID:        830105350342
      TF_IN_AUTOMATION:      "true"

    permissions:
      contents: read
      id-token: write

    steps:
      # ------------------- Checkout code -------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ------------------- ECR login ------------------------
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ------------------- Build & Push BACKEND ------------ 
      - name: Build backend image
        run: |
          docker build -f Dockerfile.backend -t backend:ci -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/backend-repo:latest .
      - name: Push backend image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/backend-repo:latest

      # ------------------- Build & Push FRONTEND -----------
      - name: Build frontend image
        run: |
          docker build -f Dockerfile.frontend -t frontend:ci -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend-repo:latest .
      - name: Push frontend image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend-repo:latest

      # ------------------- Terraform Setup -----------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      # ------------------- Terraform Init ------------------
      - name: Terraform init
        run: terraform init

      # ------------------- Terraform Validate --------------
      - name: Terraform validate
        run: terraform validate

      # ------------------- Terraform Plan ------------------
      - name: Terraform plan
        run: terraform plan -out=tfplan

      # ------------------- Terraform Apply -----------------
      - name: Terraform apply
        run: terraform apply -auto-approve tfplan

