name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      TF_IN_AUTOMATION: "true"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    # ------------------- checkout -------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # ------------------- ECR login -------------------
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    # ------------------- build & push BACKEND -------
    - name: Build backend image
      run: |
        docker build -f Dockerfile.backend \
          -t backend:ci \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/backend-repository:latest .

    - name: Push backend image
      run: |
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/backend-repository:latest

    # ------------------- build & push FRONTEND ------
    - name: Build frontend image
      run: |
        docker build -f Dockerfile.frontend \
          -t frontend:ci \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend-repository:latest .

    - name: Push frontend image
      run: |
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend-repository:latest

    # ------------------- Terraform Setup & Deploy ---
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      run: terraform -chdir=terraformfiles init

    - name: Terraform Validate
      run: terraform -chdir=terraformfiles validate

    - name: Terraform Plan
      run: terraform -chdir=terraformfiles plan -out=tfplan

    - name: Terraform Apply
      run: terraform -chdir=terraformfiles apply -auto-approve tfplan

    # ------------------- Print Frontend URL ----------
    - name: Print frontend URL
      run: |
        echo "✅ Application deployed successfully!"
        echo ""
        echo "🌐 Frontend URL:"
        terraform -chdir=terraformfiles output -raw frontend_url

